steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '.']
    env: ['PROJECT_ROOT=watchmyrepo']
  - name: 'gcr.io/cloud-builders/go'
    args: ['run', 'watchmyrepo']
    env: ['PROJECT_ROOT=watchmyrepo']
artifacts:
  objects:
    location: 'gs://watchmyrepo-248001/'
    paths: ['watchmyrepo']
